import type { Industry } from "./types";

export const industries: Industry[] = [
  {
    slug: "nigerian-smes",
    name: "Nigerian SMEs",
    problem: "You know your product is good, but the wrong people find you, or nobody does. Ad spend is unpredictable and word of mouth has a ceiling.",
    opportunity: "Most SME competitors still rely on social posting and referrals. A connected system of search, ads and WhatsApp follow-up puts you ahead.",
    system: ["Local SEO and Google Business Profile", "Lead-focused Meta and Google Ads", "A fast website with a WhatsApp path", "Simple CRM and follow-up automation"],
    services: ["seo", "paid-advertising", "lead-generation"],
    cta: "Build My Growth System",
  },
  {
    slug: "ecommerce",
    name: "E-commerce",
    problem: "Traffic comes in, but carts are abandoned and each sale costs more than it should. Customers ask the same questions on WhatsApp all day.",
    opportunity: "Better product pages, retargeting and automated customer replies raise conversion without needing more traffic.",
    system: ["Conversion-focused product pages", "Retargeting and catalogue ads", "WhatsApp order and support automation", "Product and category SEO"],
    services: ["paid-advertising", "web-development", "ai-marketing-automation"],
    cta: "Improve My Store's Sales",
  },
  {
    slug: "professional-services",
    name: "Professional Services",
    problem: "Your reputation is strong, but prospects can't find you online, and your website doesn't reflect the quality of your work.",
    opportunity: "Authority content and search visibility turn expertise into inbound enquiries from people who already trust you.",
    system: ["Positioning and founder-led content", "SEO for high-intent service searches", "A credible website with enquiry paths", "Email nurture for longer sales cycles"],
    services: ["brand-strategy", "seo", "web-development"],
    cta: "Get Found for What You Know",
  },
  {
    slug: "education",
    name: "Education",
    problem: "Enrolment windows are short, competition is intense and parents or students compare many options before contacting anyone.",
    opportunity: "Search, ads and quick follow-up capture applicants at the moment they're deciding.",
    system: ["Programme landing pages", "Search and social campaigns timed to intake", "Enquiry follow-up on WhatsApp", "Application tracking by source"],
    services: ["seo", "paid-advertising", "lead-generation"],
    cta: "Fill My Next Intake",
  },
  {
    slug: "hospitality",
    name: "Hospitality",
    problem: "Bookings depend on visibility, reviews and speed of response. Enquiries at night or on weekends go unanswered.",
    opportunity: "Local search visibility and instant replies win bookings competitors miss.",
    system: ["Local SEO and Google Business Profile", "Booking-focused website", "WhatsApp enquiry automation", "Retargeting past visitors"],
    services: ["seo", "web-development", "ai-marketing-automation"],
    cta: "Get More Direct Bookings",
  },
  {
    slug: "restaurants-food",
    name: "Restaurants & Food Businesses",
    problem: "Customers find you on social media or maps, but ordering is messy and repeat business isn't tracked.",
    opportunity: "A clear ordering path and simple follow-up turns first-time customers into regulars.",
    system: ["Google Maps and local search visibility", "Order-friendly menu and WhatsApp ordering", "Local paid campaigns around peak times", "Customer list and repeat-order messages"],
    services: ["seo", "paid-advertising", "ai-marketing-automation"],
    cta: "Bring in More Orders",
  },
  {
    slug: "technology",
    name: "Technology",
    problem: "Your product is hard to explain in a click and buyers do a lot of research before talking to sales.",
    opportunity: "Clear positioning and educational content shorten the sales cycle and attract better-fit users.",
    system: ["Product and use-case pages", "Content and SEO for problem-aware searches", "Lead magnets and demo funnels", "Lifecycle email and CRM"],
    services: ["web-development", "seo", "lead-generation"],
    cta: "Make My Product Easier to Buy",
  },
  {
    slug: "real-estate",
    name: "Real Estate",
    problem: "You get plenty of enquiries, but most aren't serious buyers. Follow-up is inconsistent and slow.",
    opportunity: "Qualification and fast response focus your team on buyers who are ready.",
    system: ["Property and location landing pages", "Lead-gen ads with qualifying questions", "WhatsApp qualification flows", "CRM pipeline with scoring"],
    services: ["paid-advertising", "lead-generation", "ai-marketing-automation"],
    cta: "Attract Serious Buyers",
  },
  {
    slug: "personal-brands",
    name: "Personal Brands",
    problem: "You're the product, but your online presence is inconsistent and doesn't show your best work.",
    opportunity: "A clear personal brand attracts speaking, clients and partnerships without constant chasing.",
    system: ["Positioning and message", "A personal website with proof", "LinkedIn and content rhythm", "Email list building"],
    services: ["brand-strategy", "web-development", "seo"],
    cta: "Build My Personal Brand",
  },
  {
    slug: "startups",
    name: "Startups",
    problem: "You need customers now on a small budget and can't afford channels that take a year to pay off.",
    opportunity: "A lean system focused on one or two channels validates demand quickly and gives you data to scale.",
    system: ["A focused launch website", "One testable paid channel", "Lead capture and simple CRM", "SEO foundations for later growth"],
    services: ["web-development", "paid-advertising", "lead-generation"],
    cta: "Launch With a Growth Plan",
  },
];

export const getIndustry = (slug: string) => industries.find((i) => i.slug === slug);
